TARGET_LIB = libbulletpsp.a
OBJS = LinearMath/btQuickprof.o \
		LinearMath/btGeometryUtil.o \
		LinearMath/btAlignedAllocator.o \
		LinearMath/btSerializer.o \
		LinearMath/btConvexHull.o \
		LinearMath/btPolarDecomposition.o \
		LinearMath/btVector3.o \
		LinearMath/btConvexHullComputer.o \
		BulletCollision/NarrowPhaseCollision/btRaycastCallback.o \
		BulletCollision/NarrowPhaseCollision/btMinkowskiPenetrationDepthSolver.o \
		BulletCollision/NarrowPhaseCollision/btSubSimplexConvexCast.o \
		BulletCollision/NarrowPhaseCollision/btGjkEpaPenetrationDepthSolver.o \
		BulletCollision/NarrowPhaseCollision/btGjkConvexCast.o \
		BulletCollision/NarrowPhaseCollision/btPersistentManifold.o \
		BulletCollision/NarrowPhaseCollision/btConvexCast.o \
		BulletCollision/NarrowPhaseCollision/btPolyhedralContactClipping.o \
		BulletCollision/NarrowPhaseCollision/btContinuousConvexCollision.o \
		BulletCollision/NarrowPhaseCollision/btGjkPairDetector.o \
		BulletCollision/NarrowPhaseCollision/btGjkEpa2.o \
		BulletCollision/NarrowPhaseCollision/btVoronoiSimplexSolver.o \
		BulletCollision/CollisionDispatch/btActivatingCollisionAlgorithm.o \
		BulletCollision/CollisionDispatch/btCollisionObject.o \
		BulletCollision/CollisionDispatch/btEmptyCollisionAlgorithm.o \
		BulletCollision/CollisionDispatch/btGhostObject.o \
		BulletCollision/CollisionDispatch/btSphereSphereCollisionAlgorithm.o \
		BulletCollision/CollisionDispatch/btSphereBoxCollisionAlgorithm.o \
		BulletCollision/CollisionDispatch/btCollisionDispatcher.o \
		BulletCollision/CollisionDispatch/btDefaultCollisionConfiguration.o \
		BulletCollision/CollisionDispatch/btSimulationIslandManager.o \
		BulletCollision/CollisionDispatch/btBoxBoxDetector.o \
		BulletCollision/CollisionDispatch/btConvexPlaneCollisionAlgorithm.o \
		BulletCollision/CollisionDispatch/btConvexConcaveCollisionAlgorithm.o \
		BulletCollision/CollisionDispatch/btBoxBoxCollisionAlgorithm.o \
		BulletCollision/CollisionDispatch/btBox2dBox2dCollisionAlgorithm.o \
		BulletCollision/CollisionDispatch/SphereTriangleDetector.o \
		BulletCollision/CollisionDispatch/btInternalEdgeUtility.o \
		BulletCollision/CollisionDispatch/btManifoldResult.o \
		BulletCollision/CollisionDispatch/btCollisionWorld.o \
		BulletCollision/CollisionDispatch/btSphereTriangleCollisionAlgorithm.o \
		BulletCollision/CollisionDispatch/btConvexConvexAlgorithm.o \
		BulletCollision/CollisionDispatch/btConvex2dConvex2dAlgorithm.o \
		BulletCollision/CollisionDispatch/btUnionFind.o \
		BulletCollision/CollisionDispatch/btCompoundCollisionAlgorithm.o \
		BulletCollision/CollisionDispatch/btHashedSimplePairCache.o \
		BulletCollision/CollisionDispatch/btCompoundCompoundCollisionAlgorithm.o \
		BulletCollision/CollisionShapes/btTetrahedronShape.o \
		BulletCollision/CollisionShapes/btShapeHull.o \
		BulletCollision/CollisionShapes/btMinkowskiSumShape.o \
		BulletCollision/CollisionShapes/btCompoundShape.o \
		BulletCollision/CollisionShapes/btConeShape.o \
		BulletCollision/CollisionShapes/btConvexPolyhedron.o \
		BulletCollision/CollisionShapes/btMultiSphereShape.o \
		BulletCollision/CollisionShapes/btUniformScalingShape.o \
		BulletCollision/CollisionShapes/btSphereShape.o \
		BulletCollision/CollisionShapes/btTriangleIndexVertexArray.o \
		BulletCollision/CollisionShapes/btBvhTriangleMeshShape.o \
		BulletCollision/CollisionShapes/btTriangleMeshShape.o \
		BulletCollision/CollisionShapes/btTriangleBuffer.o \
		BulletCollision/CollisionShapes/btStaticPlaneShape.o \
		BulletCollision/CollisionShapes/btPolyhedralConvexShape.o \
		BulletCollision/CollisionShapes/btEmptyShape.o \
		BulletCollision/CollisionShapes/btCollisionShape.o \
		BulletCollision/CollisionShapes/btConvexShape.o \
		BulletCollision/CollisionShapes/btConvex2dShape.o \
		BulletCollision/CollisionShapes/btConvexInternalShape.o \
		BulletCollision/CollisionShapes/btConvexHullShape.o \
		BulletCollision/CollisionShapes/btTriangleCallback.o \
		BulletCollision/CollisionShapes/btCapsuleShape.o \
		BulletCollision/CollisionShapes/btConvexTriangleMeshShape.o \
		BulletCollision/CollisionShapes/btConcaveShape.o \
		BulletCollision/CollisionShapes/btConvexPointCloudShape.o \
		BulletCollision/CollisionShapes/btBoxShape.o \
		BulletCollision/CollisionShapes/btBox2dShape.o \
		BulletCollision/CollisionShapes/btOptimizedBvh.o \
		BulletCollision/CollisionShapes/btHeightfieldTerrainShape.o \
		BulletCollision/CollisionShapes/btMultimaterialTriangleMeshShape.o \
		BulletCollision/CollisionShapes/btCylinderShape.o \
		BulletCollision/CollisionShapes/btScaledBvhTriangleMeshShape.o \
		BulletCollision/CollisionShapes/btStridingMeshInterface.o \
		BulletCollision/CollisionShapes/btTriangleIndexVertexMaterialArray.o \
		BulletCollision/CollisionShapes/btTriangleMesh.o \
		BulletCollision/BroadphaseCollision/btAxisSweep3.o \
		BulletCollision/BroadphaseCollision/btOverlappingPairCache.o \
		BulletCollision/BroadphaseCollision/btDbvtBroadphase.o \
		BulletCollision/BroadphaseCollision/btMultiSapBroadphase.o \
		BulletCollision/BroadphaseCollision/btDispatcher.o \
		BulletCollision/BroadphaseCollision/btBroadphaseProxy.o \
		BulletCollision/BroadphaseCollision/btQuantizedBvh.o \
		BulletCollision/BroadphaseCollision/btCollisionAlgorithm.o \
		BulletCollision/BroadphaseCollision/btDbvt.o \
		BulletCollision/BroadphaseCollision/btSimpleBroadphase.o \
		BulletCollision/Gimpact/btGImpactBvh.o\
        BulletCollision/Gimpact/btGImpactQuantizedBvh.o\
        BulletCollision/Gimpact/btTriangleShapeEx.o\
        BulletCollision/Gimpact/btGImpactCollisionAlgorithm.o\
        BulletCollision/Gimpact/btGImpactShape.o\
        BulletCollision/Gimpact/gim_box_set.o\
        BulletCollision/Gimpact/gim_contact.o\
        BulletCollision/Gimpact/gim_memory.o\
        BulletCollision/Gimpact/gim_tri_collision.o\
		BulletDynamics/Dynamics/btRigidBody.o \
		BulletDynamics/Dynamics/btSimpleDynamicsWorld.o \
		BulletDynamics/Dynamics/Bullet-C-API.o \
		BulletDynamics/Dynamics/btDiscreteDynamicsWorld.o \
		BulletDynamics/ConstraintSolver/btFixedConstraint.o \
		BulletDynamics/ConstraintSolver/btGearConstraint.o \
		BulletDynamics/ConstraintSolver/btGeneric6DofConstraint.o \
		BulletDynamics/ConstraintSolver/btGeneric6DofSpringConstraint.o \
		BulletDynamics/ConstraintSolver/btSolve2LinearConstraint.o \
		BulletDynamics/ConstraintSolver/btPoint2PointConstraint.o \
		BulletDynamics/ConstraintSolver/btTypedConstraint.o \
		BulletDynamics/ConstraintSolver/btContactConstraint.o \
		BulletDynamics/ConstraintSolver/btSliderConstraint.o \
		BulletDynamics/ConstraintSolver/btConeTwistConstraint.o \
		BulletDynamics/ConstraintSolver/btHingeConstraint.o \
		BulletDynamics/ConstraintSolver/btHinge2Constraint.o \
		BulletDynamics/ConstraintSolver/btUniversalConstraint.o \
		BulletDynamics/ConstraintSolver/btSequentialImpulseConstraintSolver.o \
		BulletDynamics/Vehicle/btWheelInfo.o \
		BulletDynamics/Vehicle/btRaycastVehicle.o \
		BulletDynamics/Character/btKinematicCharacterController.o \
		BulletDynamics/Featherstone/btMultiBody.o \
		BulletDynamics/Featherstone/btMultiBodyConstraintSolver.o \
		BulletDynamics/Featherstone/btMultiBodyDynamicsWorld.o \
		BulletDynamics/Featherstone/btMultiBodyJointMotor.o \
		BulletDynamics/Featherstone/btMultiBodyJointLimitConstraint.o \
		BulletDynamics/Featherstone/btMultiBodyConstraint.o \
		BulletDynamics/Featherstone/btMultiBodyPoint2Point.o \
		BulletDynamics/MLCPSolvers/btDantzigLCP.o \
        BulletDynamics/MLCPSolvers/btMLCPSolver.o \
		BulletSoftBody/btDefaultSoftBodySolver.o \
		BulletSoftBody/btSoftBodyRigidBodyCollisionConfiguration.o \
		BulletSoftBody/btSoftBody.o \
		BulletSoftBody/btSoftRigidCollisionAlgorithm.o \
		BulletSoftBody/btSoftBodyConcaveCollisionAlgorithm.o \
		BulletSoftBody/btSoftRigidDynamicsWorld.o \
		BulletSoftBody/btSoftBodyHelpers.o \
		BulletSoftBody/btSoftSoftCollisionAlgorithm.o
		
INCDIR = 
CFLAGS = -O2 -G0 -Wall
CXXFLAGS = $(CFLAGS) -fno-exceptions -fno-rtti
ASFLAGS = $(CFLAGS)

LIBDIR =
LDFLAGS =
LIBS = -lpspmath

PSPSDK=$(shell psp-config --pspsdk-path)
include $(PSPSDK)/lib/build.mak
